# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [ ]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [1]:
import numpy as np

**2. Print the numpy version and the configuration**

In [3]:
print(np.__version__)
print(np.show_config())

1.21.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512C

**3. Create a 1D array of zeros of size 10 of type float32**

In [5]:
np.zeros((10), dtype=np.float32)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

**4. Print the memory size of the array below**

In [9]:
Z.size

384

In [7]:
Z = np.zeros((32,12))
# Include your solution below
Z.itemsize * Z.size

3072

**5. Create a 1D array with values ranging from 10 to 58**

In [11]:
np.arange(10,59)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58])

**6. Reverse the order of the values in the vector (first element becomes last)**

In [12]:
a = np.arange(10)
# Include your solution below
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [15]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**8. Create a 3x3 identity matrix**

In [17]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**9. Find and print the maximum values of each column in the array below** 

In [23]:
Z = np.random.random((10,11))
# Include your solution below
Z.max(axis=0)

array([0.79859337, 0.94436474, 0.87360475, 0.88554429, 0.96341132,
       0.9949938 , 0.92489938, 0.88121405, 0.93458385, 0.86327942,
       0.88988427])

In [24]:
Z

array([[0.66145931, 0.80958107, 0.87360475, 0.03196657, 0.77251943,
        0.80146788, 0.92489938, 0.88121405, 0.76088114, 0.36418372,
        0.21327587],
       [0.6821754 , 0.8972905 , 0.28777008, 0.14239692, 0.51082914,
        0.07679699, 0.48176793, 0.13387787, 0.10201224, 0.37377456,
        0.56509417],
       [0.03461409, 0.09630137, 0.65641462, 0.4905062 , 0.52213585,
        0.65957851, 0.62530321, 0.64823309, 0.51957593, 0.18882772,
        0.77183504],
       [0.45846248, 0.60240525, 0.6695523 , 0.2428498 , 0.96341132,
        0.55261103, 0.18426072, 0.28373746, 0.48775124, 0.33109614,
        0.79968173],
       [0.59127086, 0.94436474, 0.74314853, 0.32883845, 0.4153611 ,
        0.60420787, 0.02069801, 0.80756856, 0.42620061, 0.86327942,
        0.64855796],
       [0.15120964, 0.12951205, 0.38680932, 0.88554429, 0.23967022,
        0.71088999, 0.18440668, 0.6337349 , 0.5430083 , 0.12188819,
        0.15114739],
       [0.40625687, 0.78989409, 0.0308801 , 0.17428797, 0.

**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [31]:
arr = np.ones((7,7))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [36]:
Z = np.ones((5,5))
# Include your solution below
np.pad(Z, 1)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

**12. Extract the integer part of the random array of positive numbers below**

In [40]:
Z = np.random.uniform(0,10,10)
# Include your solution below
print(Z)
np.floor(Z)

[7.46491763 6.88969095 3.2835943  5.23508413 2.96507498 9.66424153
 8.24617022 6.57628639 4.4975057  8.67334055]


array([7., 6., 3., 5., 2., 9., 8., 6., 4., 8.])

**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [41]:
_, a = np.indices((5,5))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [47]:
np.linspace(0, 1, 12)[1:-1]
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

**15. Create a random vector of size 10 and sort it**

In [52]:
np.sort((np.random.randn(10)))

array([-1.83877242, -1.63425417, -1.04155142, -0.83375399, -0.69432547,
       -0.47969084, -0.25818532, -0.2471375 ,  0.23099716,  1.23184258])

**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [58]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
r = np.sqrt(X**2 + Y**2)
theta = np.arctan2(Y, X)
print("r = {}".format(r))
print("theta = {}".format(theta))


r = [1.14356292 0.94500754 1.26983312 1.02969618 0.985167   0.34918709
 0.40880897 1.18239146 0.34513737 0.57170059]
theta = [0.52947051 1.42526045 0.68096498 0.3968011  0.90765082 1.53211457
 1.17552012 0.82101547 0.82030346 1.30523378]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [73]:
arr = np.random.randn(10)
print("before replacement: {}".format(arr))
arr[arr == np.max(arr)] = 0
print("after replacement: {}".format(arr))

before replacement: [ 0.70012624  0.04411566  2.04726409 -0.753488   -0.75148321  1.14617399
 -1.8970582  -0.10165375 -0.19980605  1.3308726 ]
after replacement: [ 0.70012624  0.04411566  0.         -0.753488   -0.75148321  1.14617399
 -1.8970582  -0.10165375 -0.19980605  1.3308726 ]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [86]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below
print("Z = {}".format(Z))
print("closest value: {}".format(Z[np.abs(Z - z).argmin()]))

Z = [0.30580241 0.84534436 0.05719309 0.10646828 0.29485031 0.08026077
 0.95332528 0.07197028 0.35723058 0.62418822]
closest value: 0.624188218896655


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [114]:
Z = np.arange(5)[::-1]
# Include your solution below
new_Z = np.zeros(len(Z) + (len(Z)-1)*3)
new_Z[::4] = Z
new_Z

array([4., 0., 0., 0., 3., 0., 0., 0., 2., 0., 0., 0., 1., 0., 0., 0., 0.])

**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [127]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
A * B.reshape(5,5,1)

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

**21. Swap the first and second rows of the 2D array below**

In [143]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below
print("after swapping..")
W[[0, 1], :] = W[[1, 0], :]
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

after swapping..
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [212]:
def bbox(img):
    rows = np.any(img, axis = 1)
    cols = np.any(img, axis = 0)
    r1, r2 = np.where(rows)[0][[0, -1]]
    c1, c2 = np.where(cols)[0][[0, -1]]
    return (r1,c1),(r2,c2)

from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

((29, 50), (342, 431))


**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [240]:
def moving_average(x, N = 3):
    #define your function here
    cum_sum = np.cumsum(x)
    cum_sum[N:] = cum_sum[N:] - cum_sum[:-N]
    return cum_sum[N - 1:]/N

a = np.arange(10)
N = 3
print(moving_average(a,N))

[1. 2. 3. 4. 5. 6. 7. 8.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [262]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here
np.repeat(np.arange(len(C)), C)

[0 2 1 1 2 0 1]


array([1, 1, 2, 3, 4, 4, 6])

**25. Find the most frequent value in the array below?**

In [192]:
Z = np.random.randint(0,10,50)
# Include your solution below
Z[np.bincount(Z).argmax()]

7

**26. Write a function to return the n largest values of an array** 

In [185]:
def nlargest(a,n = 5):
    # Include your solution here
    return a[np.argpartition(-a, n)][:n]

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    

[9999 9998 9997 9996 9995]
